DROP DATABASE IF EXISTS holypenguin;

CREATE DATABASE holypenguin;

USE holypenguin;

CREATE TABLE Users(
  usr_ID_PK INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  usr_Nickname VARCHAR(15) NOT NULL UNIQUE,
  usr_Firstname Varchar(20) NOT NULL,
  usr_Lastname Varchar(20) NOT NULL,
  usr_Password CHAR(128) NOT NULL,
  usr_Email Varchar(100) NOT NULL UNIQUE,
  usr_Admin BOOLEAN NOT NULL
);

CREATE TABLE Games(
  gm_ID_PK INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  gm_Name VARCHAR(20) NOT NULL,
  gm_Type VARCHAR(20),
  gm_Version VARCHAR(20)
);

CREATE TABLE User2Game(
  usr2gm_ID_PK INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  gm_ID_FK INT NOT NULL,
  usr_ID_FK INT NOT NULL,
  usr2gm_Port INT NOT NULL UNIQUE,
  CONSTRAINT fk_gm_id
    FOREIGN KEY (gm_ID_FK) REFERENCES Games(gm_ID_PK)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT fk_usr_id
    FOREIGN KEY (usr_ID_FK) REFERENCES Users(usr_ID_PK)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

SHOW DATABASES;
SHOW TABLES;
